### ISSUE TITLE
Trivial, but might be of interest - test groups

### ISSUE THREAD

**Issue by ghost** [katydid/haslapse#1]
Tasty or hspecs features for grouping tests might be interesting to you

**Comment by awalterschulze** [comment]
Cool Thank you.  Both look promising, given a very quick skim.  
I look into this in more depth later :)
This is definitely a part of the project where I feel like a need something extra.

**Comment by awalterschulze** [comment]
I added tasty.
It looks MUCH better.
Thanks again.

**Comment by ghost** [comment]
If you get your PVP bounds set up and are willing to keep the library up to
date every few months as dependencies change, you get free test coverage
reports from hackage matrix if you publish to hackage -
https://matrix.hackage.haskell.org/package/postgresql-typed

Alternatively, you can use Travis using the FP Complete or hvr versions of
multi-travis-ghc scripts

**Comment by awalterschulze** [comment]
https://github.com/katydid/katydid-haskell/commit/dffbd26071ab0e131b4b44c3097048703a155a1a

**Comment by awalterschulze** [comment]
Yes I think publishing to hackage is a good idea.  Didn't know I got free testing as well.  Thats really cool :)

**Comment by awalterschulze** [comment]
I have added it to hackage
https://hackage.haskell.org/package/katydid-0.1.0.0
Do I simply wait to get a report from hackage matrix or is there something I still need to do?

**Comment by ghost** [comment]
I think it runs nightly

**Comment by ghost** [comment]
I think it only checks for compiling against different GHC's, doesn't appear to run test-suites. Travis will probably help you more for now, since it will run your tests. Hackage will want dependency bounds, which is probably too much detail for you to get into into currently.

**Comment by awalterschulze** [comment]
I have setup travis as suggested by you and stackage and also added my package to stackage.
Hackage has not asked for any dependency bounds though.
