### ISSUE TITLE
Zip module, consider ADT instead of special ints

### ISSUE THREAD

**Issue by ghost** [katydid/haslapse#2]
data ZipEntry = Val Int | Special1 | Special2

I don't read deep enough yet to give proper names for special1, etc, with respect to -1 and -2

**Comment by awalterschulze** [comment]
Fair Point :)

**Comment by awalterschulze** [comment]
Done.
Thank you for the tip.

**Comment by awalterschulze** [comment]
https://github.com/katydid/katydid-haskell/commit/54b59b47da463d027071fb09fdaae265f9452537
