### ISSUE TITLE
Xml - consider simple helpers

### ISSUE THREAD

**Issue by ghost** [katydid/haslapse#3]
functions "maybe" and "either" are handy... Or try to internalize more of the prelude.

**Comment by ghost** [comment]
Err base, not just prelude.

**Comment by awalterschulze** [comment]
I think I need more of a hint here to understand what you are saying?

**Comment by ghost** [comment]
https://hackage.haskell.org/package/base-4.10.0.0/docs/Data-Maybe.html
https://hackage.haskell.org/package/base-4.10.0.0/docs/Data-Either.html

if you click view source also, you will notice how similar the impls are to your code.

**Comment by awalterschulze** [comment]
Ah, sorry I was a little slow on the uptake.
I have implemented this now :)
Thank you very much.

**Comment by awalterschulze** [comment]
https://github.com/katydid/katydid-haskell/commit/247f1acddc235da998562038db05d5d53479656a
