### ISSUE TITLE
Fewer type aliases?

### ISSUE THREAD

**Issue by ghost** [katydid/haslapse#5]
Somewhat of a style choice... But I would tend towards not aliasing the types or using a full newtype

**Comment by awalterschulze** [comment]
Where do you think it is over used?

**Comment by ghost** [comment]
I basically wouldn't use them in any of your examples. I might use newtype for aliases. I wouldn't say over used. Some people like them.

**Comment by awalterschulze** [comment]
Hmmm maybe you can point me to a specific type?  I am still struggling to follow you.  I am sorry.

**Comment by ghost** [comment]
`type Zipper = [Int]`
I would new type that one or just use [Int], if you don't think much information is added.

**Comment by awalterschulze** [comment]
Ah ok.
Now I am with you.

**Comment by awalterschulze** [comment]
I did a few.
I prefer the newtype over aliases for the types that I expose.
But I still think some type names helps to make reading the code easier, so I did keep some internal type aliases.
Thanks again.
This definitely helped.

**Comment by awalterschulze** [comment]
https://github.com/katydid/katydid-haskell/commit/259714beb451ec7b0e5ea77c9194ed0dee10441a
