### ISSUE TITLE
Missing files for test suite

### ISSUE THREAD

**Issue by snoyberg** [katydid/haslapse#7]
This usually means you're missing some `other-modules` info in your .cabal file:

```
Building test suite 'katydid-test' for katydid-0.1.0.0..
[1 of 1] Compiling Main             ( test/Spec.hs, dist/build/katydid-test/katydid-test-tmp/Main.o )

test/Spec.hs:10:1: error:
    Could not find module ‘ParserSpec’
    Use -v to see a list of the files searched for.
   |
10 | import qualified ParserSpec
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

test/Spec.hs:11:1: error:
    Could not find module ‘Suite’
    Use -v to see a list of the files searched for.
   |
11 | import qualified Suite
   | ^^^^^^^^^^^^^^^^^^^^^^

test/Spec.hs:12:1: error:
    Could not find module ‘RelapseSpec’
    Use -v to see a list of the files searched for.
   |
12 | import qualified RelapseSpec
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by awalterschulze** [comment]
I am also running on travis using the travis file provided by stackage docs and I am not seeing this problem.
How do I reproduce this problem?

**Comment by snoyberg** [comment]
Unpack the tarball that's on Hackage and try building from inside there, e.g. `stack unpack katydid && cd katydid-* && stack init && stack test` should do the trick.

**Comment by awalterschulze** [comment]
Ah ok cool.  I see.  I can reproduce.

I used `stack sdist` to create the tar ball, what command should I have used?

**Comment by snoyberg** [comment]
That's the right command. As I mentioned initially: you need to modify your cabal file to include an other-modules section for the test suite. As an example: https://github.com/snoyberg/conduit/blob/5e2a7bcd4ec2755a9597b2f0dc3e15800c3d42e6/conduit-extra/conduit-extra.cabal#L96

**Comment by awalterschulze** [comment]
Ah thanks :)

I have updated hackage with the new file
https://hackage.haskell.org/package/katydid-0.1.1.0
created by this new commit
https://github.com/katydid/katydid-haskell/commit/77fe190da9e115de857907b2871caacb3ed1e771

**Comment by snoyberg** [comment]
Thanks!

**Comment by awalterschulze** [comment]
No no no.  I am thanking you @snoyberg 
Stackage is the reason I tried using haskell again.  cabal hell was too much for me.
Thanks for maintaining such a great project.

**Comment by snoyberg** [comment]
Happy to hear it 👍
