### ISSUE TITLE
Concise use cases

### ISSUE THREAD

**Issue by ghost** [katydid/haslapse#8]
Can you mention a few real world use cases you have in mind for this, and point out where this fits within prior work? I skimmed docs briefly, but I don't have a strong understanding of when I would choose this over other options. 

Also, when would I choose this, if I am exclusively dealing with json?

Would I want to use this validating a tree of data expressed as in-memory Haskell data types?

**Comment by awalterschulze** [comment]
The haskell version needs some more docs and I still need to update the general docs to include more haskell http://katydid.github.io/
I am also working on a rewrite of the Expr.hs to allow users to add their own functions, as is possible in the Go version.

The idea is that you can use this language to validate any type of tree and use it for filtering large amounts of trees.   

The Go version of this project originated out of a real world use case.  We were writing a distributed database and we used this language to filter our metadata.  By pushing the expression down onto all nodes (predicate pushdown) we could minimize the amount of network required to return all results.  

It also allowed us to support multiple encoding formats.  So if you are using just json then you might also imagine a time where you will upgrade your encoding format and still have to support json for backwards compatibility.  We needed this to upgrade from a custom binary encoding to a protobuf encoding.

I am also trying to figure out other use cases.  I think with capturing there will be more use cases.  But that still requires some research.  Until then I only see filtering of massive amounts of data or encoding agnostic validation.

**Comment by ghost** [comment]
If katydid ended up focusing on json and it provided a very rich DSL for validation with implementations in Java, Javascript, and Haskell, then I would probably use it for databrary/datavyu. Haskell might be a great place to flesh out the DSL interface.

**Comment by awalterschulze** [comment]
I am very open to adding a rich DSL.  I will probably get to that in future.

The cross language [testsuite](https://github.com/katydid/testsuite) should help someone who wants to contribute support for Java and Javascript.

For now I want to get the haskell implementation on par with the Go implementation.  The following features are missing:
  - user defined functions (I am focusing on this)
  - protobuf support

Research wise I am focusing on trying to add capturing (partial unmarshaling).  This I will probably add to Haskell first.

Sorry to disappoint, but I am only one person, doing this in my part time.
I think once I have done capturing, then I can really push for more implementations and start marketing this language.

**Comment by awalterschulze** [comment]
Really good to hear about more use cases.  Thanks for letting me know.

**Comment by ghost** [comment]
No rush, just letting you know when you get there. I will also keep shopping for validation language options that exist, to see what my ideal is.

We may chip in on a Java port, if we decide that katydid is what we are looking for. CC: @theowolf

**Comment by ghost** [comment]
I would try to study type-level DSL's in Haskell. That area has yielded some beautiful engineering results for a while now. Talk with DSL designers at Haskell meetups about their vision for a DSL for validation.

**Comment by awalterschulze** [comment]
Good idea.  Will do :)
Thanks again.  This is very encouraging.
