### ISSUE TITLE
Utilities for tagged types

### ISSUE THREAD

**Issue by ghost** [katydid/haslapse#9]
Ideally, when I have external data, I want to:
- parse it
- validate it
- construct a new value with a type tagged to note it has been validated

Maybe you can address the final step of creating tagged types?

**Comment by awalterschulze** [comment]
Ok so instead of filter

```haskell
filter :: Tree t => Refs -> [[t]] -> [[t]]
```

you would like

```haskell
data Tagged a = Valid a | Invalid a

filter :: Tree t => Refs -> [[t]] -> [Tagged [t]]
```

Or what did you have in mind?

**Comment by ghost** [comment]
Light integration with https://hackage.haskell.org/package/tagged-0.8.5/docs/Data-Tagged.html

**Comment by awalterschulze** [comment]
Tagging looks super interesting.

I am still a Haskell beginner.  I am trying to transition my life from Go to Haskell.

Do you have a suggestion of how I could apply Tagging to this Project.   I see its used by jsonschema, so its sounds appropriate, but what is the use case for tagging.  If I understand correctly it allows you to tag a value with another value to create a type, but that sounds like it requires dependent types, which I was under the impression that haskell did not posses.

**Comment by ghost** [comment]
I am only intermediate myself, but I have been around parts of Haskell for a while. The more advanced type parts I am still getting familiar with.

elm-tagged documentation has an example of using tagged type generally. In your case, I was speculating about something similar to what you proposed, but using the standard tagged type instead of a new type you define.


```filter :: Tree t => Refs -> [[t]] -> [[Tagged Valid t]]```

where Valid is defined by your library. I haven't thought this through much and also don't feel pressure to focus on this if you have other fruitful ideas that require less complexity. It's best for a beginner to be prolific rather than dive too far into advanced areas.

**Comment by awalterschulze** [comment]
elm documentation helped a lot thanks :)  Their documentation is really geared towards beginners.

If we are only tagging valid types then we could easily create a map function that simply tags all the return trees.

```haskell
filterTagged :: Tree t => Refs -> [[t]] -> [Tagged Valid [t]]
filterTagged g ts = map (Tagged Valid) (filter g ts)
```

I don't know how much value this adds?

I would have loved this

```haskell
filterTagged :: Tree t => (g : Refs) -> [[t]] -> [Tagged g [t]]
filterTagged g ts = map (Tagged g) (filter g ts)
```

Where the resulting trees are tagged with the grammar that they satisfy.

**Comment by ghost** [comment]
First one seems moderately useful, but your call. Maybe Reddit or irc will have more opinions.

The second example sounds like a closer fit for proxy instead of tagged, according to some discussion threads I reviewed.

**Comment by awalterschulze** [comment]
I think the second one is simple enough to implement outside of the library.  That way you could also do more interesting things like.

```haskell
-- a little hack for demo
must :: Either String Refs -> Refs
must (Right r) = r
must (Left s) = error s
-- create refs for trees that can tell you whether monkeys are smart
monkeyPredicate = must $ parseGrammar ".MonkeysSmart :: $bool"

-- not sure if this is correct syntax, but make a type for types which can tell you whether monkeys are smart
data MonkeyPredicate = MonkeyPredicate

filterMonkeys :: Tree t => [[t]] -> [Tagged MonkeyPredicate [t]]
filterMonkeys ts = map (Tagged MonkeyPredicate) filter monkeyPredicate ts 

-- a function that only uses trees that can tell whether monkeys are smart, granted a bool type is a bad example here, because it would have been done better with two filters, but for ints this might have been useful.
voteForMonkeys :: Tree t => [Tagged MonkeyPredicate [t]] -> (Int, Int)
```

**Comment by ghost** [comment]
I read your note, but I probably won't respond for a while as I will be focused on work. Feel free to close this or proceed as you wish.

**Comment by awalterschulze** [comment]
I am going to close for now, but if you or someone comes along and explains why the Tagged part should be in the library and not outside, then I will be very eager to listen.

**Comment by awalterschulze** [comment]
May I ask what you might have intended to use this for?
